spring:
  application:
    name: store

  datasource:
    url: jdbc:h2:~/test-metric.db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include:
          - prometheus
          - health
